title: Won-tak Joo
logo: /assets/img/wontak.jpg
description: <b>PhD Candidate</b><br><b>Department of Sociology</b><br><b>University of Wisconsin–Madison</b><br><small>© 2021 Won-tak Joo  
theme: jekyll-theme-minimal
