title: Won-tak Joo
logo: /assets/img/wontak.jpg
description: >
  <b>Assistant Professor</b>
  <br>
  <b>Sociology and Criminology & Law</b>
  <br>
  <b>University of Florida</b>
  <br><br>
  <a href = "mailto: wjoo@ufl.edu">E-mail</a> | <a href = "https://twitter.com/1takjoo">Twitter</a>
  <br>
  <a href = "https://github.com/1takjoo">Github</a>
  <br>
  <a href = "https://scholar.google.com/citations?user=FG6jPj4AAAAJ&hl=en&authuser=3">Google Scholar</a>
  <br><br>
  <small>© 2023 Won-tak Joo</small>
  <br>
  <small>Theme by <a href="https://github.com/orderedlist">orderedlist</a></small>
theme: jekyll-theme-minimal
